### ISSUE TITLE
IOS not building

### ISSUE THREAD

**Issue by shebkhan** [EddieKamau/ussd_advanced#1]
Getting No visible @interface for 'UssdAdvancedPlugin' declares the selector 'directCall:'
![image](https://user-images.githubusercontent.com/1731271/127921237-f63ad40b-1505-4eea-8f2a-f1351c4341c7.png)

**Comment by shebkhan** [comment]
Can you please help

**Comment by EddieKamau** [comment]
There was a missing '}', try using the plugin from Github. If it fixes the issue kindly notify me so that I can publish with the new changes.
ussd_advanced:
    git: git://github.com/EddieKamau/ussd_advanced.git

**Comment by shebkhan** [comment]
Yes it seems to be working many thanks.

One question ON IOS can we get the response as string back?

Also in IOS when I try to execute any code it thows a bottom sheet with CALL Number button can we by pass it?

**Comment by EddieKamau** [comment]
For security reasons, IOS doesn't support USSD as an API.
Hence you can't get the response nor bypass the dialer.
